### Create a new user with address
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "userType": "CUSTOMER",
  "password": "secret",
  "firstName": "John",
  "lastName": "Doe",
  "phone": "06 123456789",
  "userPoints": 0,
  "address": {
    "street": "123 Main Street",
    "city": "Amsterdam",
    "postalCode": "1011AA",
    "houseNumber": 0,
    "subHouseNumber": "test"
  }
}


### Login and store JWT
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "secret"
}

> {% client.global.set("token", response.body.token); %}

### Create a new car
POST {{baseUrl}}/car/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "fuelType": "ICE",
  "userId": 1,
  "bodyType": "SEDAN",
  "brand": "Toyota",
  "modelYear": "2022",
  "model": "Supra",
  "licensePlate": "KTR-123-A",
  "mileage": "34000",
  "createdStamp": "2020-08-30T18:43",
  "carImages": [
    {
      "image": "base64EncodedImageStringHere"
    },
    {
      "image": "anotherBase64EncodedImageStringHere"
    }
  ]
}

### Get personal cars (JWT secured)
GET {{baseUrl}}/personal/cars
Accept: application/json
Authorization: Bearer {{token}}
