ktor:
    application:
        modules:
            - rmc.ApplicationKt.module
    deployment:
        port: 8080

jwt:
    domain: "https://localhost/"
    audience: "myAudience"
    realm: "RentACar"
    secret: "secret"