### Create a new car
POST http://localhost:8080/advertisement/create
Content-Type: application/json
Authorization: Bearer {{ token.token }}

{
  "carId": 5,
  "address": {
    "street": "1234 Main Street",
    "city": "Amsterdam",
    "postalCode": "1011AA",
    "houseNumber": 0,
    "subHouseNumber": "test"
  },
  "availableFrom": "2020-08-30T18:43",
  "availableUntil": "2020-08-30T18:43",
  "price": 99.99
}