### Create a new car
POST http://localhost:8080/car/create
Content-Type: application/json
Authorization: Bearer {{ token.token }}

{
  "fuelType": "ICE",
  "bodyType": "SEDAN",
  "brand": "Toyota",
  "modelYear": "2022",
  "model": "Supra",
  "licensePlate": "KTR-123-Y",
  "mileage": "34000",
  "createdStamp": "2020-08-30T18:43",
  "carImages": [
    {
      "image": "base64EncodedImageStringHere"
    },
    {
      "image": "anotherBase64EncodedImageStringHere"
    }
  ]
}

### Update existing car
PUT http://localhost:8080/car/update/3
Content-Type: application/json
Authorization: Bearer {{ token.token }}

{
  "fuelType": "ICE",
  "bodyType": "SEDAN",
  "brand": "Toyota",
  "modelYear": "2023",
  "model": "Supra",
  "licensePlate": "KTR-123-B",
  "mileage": "34500",
  "createdStamp": "2025-10-23T10:00:00",
  "carImages": [
    { "image": "image1_base64_or_url_here" },
    { "image": "image2_base64_or_url_here" }
  ]
}
