### Rent advertisement
POST http://localhost:8080/rent/advertisement
Content-Type: application/json
Authorization: Bearer {{ token.token }}

{
  "advertisementId": 5,
  "rentalStatus": "PENDING",
  "pickUpDate": "2025-10-18T14:30:00",
  "returningDate": "2025-10-18T14:30:00"
}

### Cancel rental
POST http://localhost:8080/rental/cancel/7
Content-Type: application/json
Authorization: Bearer {{ token.token }}

### Approve rental
POST http://localhost:8080/rental/approve/6
Content-Type: application/json
Authorization: Bearer {{ token.token }}
