POST http://localhost:8080/rental/trip/register
Content-Type: application/json
Authorization: Bearer {{ token.token }}

{
  "rentalId": 6,
  "startMileage": 12000,
  "endMileage": 12450,
  "startDate": "2025-10-18T09:00:00",
  "endDate": "2025-10-18T17:30:00"
}
