### Create a new car
POST http://localhost:8080/advertisement/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteUF1ZGllbmNlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvIiwidXNlcklkIjoxLCJleHAiOjE3NjExNDM1MzR9.cFu5e82ATHJyHYYNc-oiHK_vbsRGNP1HHqRFcdE4rQY

{
  "carId": 1,
  "address": {
    "street": "123 Main Street",
    "city": "Amsterdam",
    "postalCode": "1011AA",
    "houseNumber": 0,
    "subHouseNumber": "test"
  },
  "pickUpDate": "2020-08-30T18:43",
  "returningDate": "2020-08-30T18:43",
  "price": 99.99
}