### Get car by ID
GET http://localhost:8080/car/show/5
Accept: application/json
Authorization: Bearer {{ token.token }}

### Get car personal cars
GET http://localhost:8080/personal/cars
Accept: application/json
Authorization: Bearer {{ token.token }}

