name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and run Ktor app
        run: |
          ./gradlew build
          nohup java -jar build/libs/*.jar &
          sleep 10

      - name: Install JetBrains HTTP Client CLI
        run: |
          curl -L https://github.com/JetBrains/http-client-cli/releases/download/v1.0.2/http-client-cli-1.0.2.zip -o cli.zip
          unzip cli.zip -d cli
          chmod +x cli/bin/jb

      - name: Run HTTP tests
        run: |
          ./cli/bin/jb http-client run test/api.http --env local
